### ISSUE TITLE
Multiple third level forms

### ISSUE THREAD

**Issue by 8cylinder** [BertrandBordage/django-super-inlines#1]
When adding a second third level form, the forms get confused, eg:

```
owner:
    house:
        1. room
        2. hallway
```
1. The "Add another room" text is the same for both.
2. Clicking "Add another room" for room does nothing.
3. Clicking "Add another room" for hallway adds two fieldsets with two forms in each, which is one room and one hall in each fieldset.

I'm using Django 1.8

B.t.w, this is an awesome piece of work you did, it's going to come in very handy.

**Comment by BertrandBordage** [comment]
Thanks :)

I found where the issue was coming from, and I fixed it with 84c29590ffd1cf09bfd889b20e23da9cb3190fc7.
Could you test it by installing the specific commit and confirm me it works? Simply run `pip install https://github.com/BertrandBordage/django-super-inlines/archive/84c2959.tar.gz`

I’ll then upload a new minor release to PyPI.
As I mentioned, the program has no unit tests yet, but I carefully tested manually it for this specific structure:
Owner → House → Hallway

Bugs can be seen on other structures such as yours, but they will be easy to fix, now that the JS is clean and that I fully understand inlines :) So please keep reporting bugs while it’s still fresh in my mind!

**Comment by 8cylinder** [comment]
Looks like its fixed. Good job.

**Comment by BertrandBordage** [comment]
Thanks! I released 0.1.2 on PyPI.
